export const Strings = {
  // App Title
  APP_TITLE: 'Arivu AI',

  // Login Screen
  LOGIN: {
    TITLE: 'Arivu AI',
    EMAIL_PLACEHOLDER: 'Email',
    PASSWORD_PLACEHOLDER: 'Password',
    LOGIN_BUTTON: 'Login',
    REGISTER_LINK_TEXT: "Don't have an account? ",
    REGISTER_LINK: 'Register',
    EMAIL_ERROR: 'Please enter a valid email address',
  },

  // Register Screen
  REGISTER: {
    TITLE: 'Create Account',
    FULL_NAME_PLACEHOLDER: 'Full Name',
    DATE_PLACEHOLDER: 'DD/MM/YYYY',
    BOARD_PLACEHOLDER: 'Select Board',
    CLASS_PLACEHOLDER: 'Select Class',
    EMAIL_PLACEHOLDER: 'Email',
    PASSWORD_PLACEHOLDER: 'Password',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm Password',
    REGISTER_BUTTON: 'Register',
    PROGRESS_HEADER: 'Registration Progress:',
    PROGRESS_COMPLETE: ' - Complete!',
    SUCCESS_TITLE: 'Registration Successful!',
    BOARD_OPTIONS: ['State Board', 'CBSE'],
    CLASS_OPTIONS: ['5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th'],
  },

  // Home Screen
  HOME: {
    HEADER_TITLE: 'Dashboard',
    HEADER_SUBTITLE: 'Welcome, {name}',
    TOTAL_TESTS_LABEL: 'Total Tests',
    AVG_SCORE_LABEL: 'Avg Score',
    OVERALL_ASSESSMENT_TITLE: 'Overall Assessment Result',
    OVERALL_ASSESSMENT_SUBTITLE: 'Review and learn from incorrect answers',
    STUDY_BUTTON: 'Study',
    TAKE_TEST_BUTTON: 'Take Test',
    BEST_SCORE_LABEL: 'Best Score',
    ACTIVE_ASSESSMENTS_LABEL: 'Active Assessments',
    COMPLETED_LABEL: 'Completed',
  },

  // Profile Screen
  PROFILE: {
    TITLE: 'Profile',
    NO_USER_DATA_TITLE: 'No User Data',
    NO_USER_DATA_SUBTITLE: 'Please register to view your profile',
    PERSONAL_INFO_TITLE: 'Personal Information',
    ACADEMIC_INFO_TITLE: 'Academic Info',
    PERSONAL_DETAILS_TITLE: 'Personal Details',
    NAME_LABEL: 'Name:',
    GENDER_LABEL: 'Gender',
    EMAIL_LABEL: 'Email:',
    DOB_LABEL: 'Date of Birth:',
    BOARD_LABEL: 'Board:',
    CLASS_LABEL: 'Class:',
    STATUS_LABEL: 'Status:',
    ACTIVE_STATUS: 'Active',
    INACTIVE_STATUS: 'Inactive',
    LOGOUT_BUTTON: 'Logout',
  },

  // Validation Messages
  VALIDATION: {
    NAME_REQUIRED: 'Name is required',
    NAME_MIN_LENGTH: 'Name must be at least 3 characters long',
    NAME_MAX_LENGTH: 'Name must be less than 50 characters',
    NAME_INVALID_CHARS: 'Name can only contain alphabets and spaces',
    EMAIL_REQUIRED: 'Email is required',
    EMAIL_TOO_LONG: 'Email is too long',
    EMAIL_MUST_CONTAIN_AT: 'Email must contain @',
    EMAIL_INVALID_FORMAT: 'Invalid email format',
    EMAIL_LOCAL_PART_TOO_LONG: 'Email local part is too long',
    EMAIL_INVALID_START_END: 'Email cannot start or end with dots or hyphens',
    EMAIL_INVALID_DOMAIN_CHARS: 'Invalid domain characters',
    EMAIL_INVALID_DOMAIN_FORMAT: 'Invalid domain format',
    EMAIL_VALID_FORMAT: 'Please enter a valid email address',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
    PASSWORD_MAX_LENGTH: 'Password must be less than 20 characters',
    PASSWORD_UPPERCASE: 'Password must contain at least one uppercase letter',
    PASSWORD_LOWERCASE: 'Password must contain at least one lowercase letter',
    PASSWORD_NUMBER: 'Password must contain at least one number',
    PASSWORD_SPECIAL: 'Password must contain at least one special character (!@#$%^&*)',
    PASSWORD_NO_SPACES: 'Password cannot contain spaces',
    CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
    PASSWORDS_NOT_MATCH: 'Passwords do not match',
    BOARD_REQUIRED: 'Board is required',
    CLASS_REQUIRED: 'Class is required',
    DOB_REQUIRED: 'Date of birth is required',
  },

  // Common
  COMMON: {
    LOADING: 'Loading...',
    NOT_SPECIFIED: 'Not specified',
    ERROR: 'Error',
    SUCCESS: 'Success',
    CANCEL: 'Cancel',
    OK: 'OK',
    SAVE: 'Save',
    EDIT: 'Edit',
    DELETE: 'Delete',
    BACK: 'Back',
    NEXT: 'Next',
    PREVIOUS: 'Previous',
    DONE: 'Done',
  },
};

